export const FETCH_MOVIES = "FETCH_MOVIES";
export const SEARCHED_MOVIE = "SEARCHED_MOVIE";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_TOPRATED_MOVIES = "FETCH_TOPRATED_MOVIES";
